---
- name: "Installation - Copy klaytn binary"
  become: yes
  copy:
    src: "{{ bin_dir }}/{{ klaytn_binary_name }}"
    dest: "/bin/{{ klaytn_binary_name }}"
    mode: preserve

- name: "Installation - Copy klaytn init.d script"
  become: yes
  copy:
    src: "{{ bin_dir }}/{{ klaytn_daemon_name }}"
    dest: "/etc/rc.d/init.d/{{ klaytn_daemon_name }}"
    mode: preserve

- name: "Configuration - Make configuration directory"
  become: yes
  file:
    path: "/etc/{{ klaytn_daemon_name }}/conf"
    state: "directory"

- name: "Configuration - Template klaytn configuration"
  become: yes
  template:
    src: "klaytn.conf.j2"
    dest: "/etc/{{ klaytn_daemon_name }}/conf/{{ klaytn_daemon_name }}.conf"

- name: "Initialization - Create klaytn directory"
  become: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
  - "{{ klaytn_conf.DATA_DIR }}"
  - "{{ klaytn_conf.LOG_DIR }}"

- name: Check if {{ klaytn_daemon_name }} service exists
  stat:
    path: /etc/systemd/system/{{ klaytn_daemon_name }}.service
  register: kaia_service
  when: inventory_hostname in groups[klaytn_node_type]

- name: Create systemd service file for {{ klaytn_daemon_name }}
  become: yes
  template:
    src: "service.j2"
    dest: "/etc/systemd/system/{{ klaytn_daemon_name }}.service"
    mode: '0644'
  when: 
    - inventory_hostname in groups[klaytn_node_type]
    - not kaia_service.stat.exists

- name: Reload systemd daemon
  become: yes
  systemd:
    daemon_reload: yes
  when: 
    - inventory_hostname in groups[klaytn_node_type]
    - not kaia_service.stat.exists
