---
- name: "Install docker"
  become: yes
  shell: "yum update -y && yum install docker -y"
  when:
    ansible_distribution == 'Amazon'
  tags:
  - docker

- name: "Install docker"
  become: yes
  shell: "curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh"
  when:
    ansible_distribution != 'Amazon'
  tags:
  - docker

- name: "Install python3"
  become: yes
  yum: 
    name: python3
    state: present
  when:
    ansible_distribution != 'Amazon'
  tags:
  - docker

- name: "Start docker daemon"
  become: yes
  systemd:
    name: docker
    state: started
    enabled: yes
  tags:
  - docker

- name: Install pip 
  shell: "curl -fsSL https://bootstrap.pypa.io/pip/3.6/get-pip.py -o get-pip.py && python3 get-pip.py"
  become: yes
  when:
    ansible_distribution != 'Amazon'
  tags:
  - docker

- name: Install pip
  shell: "curl -fsSL https://bootstrap.pypa.io/pip/get-pip.py -o get-pip.py && python3 get-pip.py"
  become: yes
  when:
    ansible_distribution == 'Amazon'
  tags:
  - docker


- name: Install docker python package
  become: yes
  pip:
    name: docker
    extra_args: "--ignore-installed"
  tags:
  - docker
