---
- name: "Download genesis.json for {{ kaia_conf.NETWORK }}"
  become: yes
  get_url:
    url: "https://packages.kaia.io/{{ kaia_conf.NETWORK }}/genesis.json"
    dest: "/etc/{{ kaia_daemon_name }}/genesis.json"
    mode: '0440'
  when:
  - not is_service_chain

- name: "Check downloaded chaindata file exists"
  become: yes
  stat:
    path: "{{ kaia_conf.DATA_DIR }}/chaindata.tar.gz"
    get_checksum: no
  register: check_chaindata_compress_file

- name: Download the latest chaindata from packages.kaia.io
  become: yes 
  get_url:
    url: "https://packages.kaia.io/{{ kaia_conf.NETWORK }}/chaindata/kaia-{{ kaia_conf.NETWORK }}-chaindata-{{ kaia_chaindata_timestamp }}.tar.gz"
    dest: "{{ kaia_conf.DATA_DIR }}/chaindata.tar.gz"
    mode: '0644'
    force: yes
    validate_certs: no
  register: download_result
  retries: 3
  delay: 5
  until: download_result is success
  when: not check_chaindata_compress_file.stat.exists
  tags:
    - chaindata

- name: Verify downloaded chaindata file
  become: yes
  command: "file {{ kaia_conf.DATA_DIR }}/chaindata.tar.gz"
  register: file_check
  changed_when: false
  when: not check_chaindata_compress_file.stat.exists
  tags:
    - chaindata

- name: Fail if downloaded file is not a valid gzip archive
  fail:
    msg: "Downloaded file is not a valid gzip archive"
  when: 
    - not check_chaindata_compress_file.stat.exists
    - "'gzip compressed data' not in file_check.stdout"
  tags:
    - chaindata

- name: Unarchive chaindata
  become: yes
  unarchive:
    src: "{{ kaia_conf.DATA_DIR }}/chaindata.tar.gz"
    dest: "{{ kaia_conf.DATA_DIR }}"
    remote_src: yes
  when: not check_chaindata_compress_file.stat.exists
  tags:
    - chaindata
